name: Publish Docker Image
on:
  release:
    types:  [published]
jobs:
  name: Push Docker image to Docker Hub
  runs-on: apline-latest
  steps:
    - name: Check out the repo
      uses: actions/checkout@v2
    - name: Push to Docker Hub
      uses: docker/build-push-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        repostiory: namespace/repository
        tag_with_ref: true
